### ISSUE TITLE
Unknown Archives being made.

### ISSUE THREAD

**Issue by IanWONeill** [nshusa/better-sprite-packer-gui#12] opened 2017-09-12 23:02 UTC
I was working on writing basic tutorials as usual, then I noticed I had maybe 36? Archives.
So I removed the cache and started a fresh with a Clean 317 and started over. I noticed that when I had finished packing files inside the versionlist and config archives - repacked to idx0 : Noticed this.

![untitled](https://user-images.githubusercontent.com/20154372/30352266-f9dd75ca-9816-11e7-9b31-0aa3b19bb33e.png)

Any idea as to why that's happening?

Also worth noting that rsam can't remove the Unknown Archive, though right-click remove reduces its size to 0. It cannot be renamed.

**Comment by nshusa** [comment] 2017-09-12 23:51
@IanWONeill Can walk me through the steps you took so I can try to reproduce the issue?

What files did you pack into versionlist? Add them one at a time and find out what file causes the issue.

**Comment by IanWONeill** [comment] 2017-09-13 00:04
So its pretty easy to reproduce, I made a gif but - Load cache > do anything (or nothing) > Repack the Index.

![heks9yuytz](https://user-images.githubusercontent.com/20154372/30353674-6d12a2f6-981f-11e7-83d7-aa6a13338ce6.gif)

Its an odd thing, the file size is different each time. You will see index 9 as 0 in size as ive right-click removed as mentioned before. Though youll notice 10 appearing once I repack.

**Comment by nshusa** [comment] 2017-09-13 00:37
@IanWONeill Why are you selecting "main_file_cache.idx0" for repack? That's probably the issue. You're not using the program properly. When you right click -> repack you select the directory containing the gzipped files. If you are packing archives you don't need to use that repack function because the program automatically builds your cache.

**Comment by IanWONeill** [comment] 2017-09-13 00:43
Haha, I see my issue 👍 sorry about that. That made me laugh.
When you realise you've been doing it wrong the whole time -.-"

**Comment by nshusa** [comment] 2017-09-13 00:51
@IanWONeill Does it work now? If so I'm going to close this issue. I'll add some validation for that for the next patch.

**Comment by IanWONeill** [comment] 2017-09-13 01:00
Thanks for the time man. And more Validation will be helpful - I've just went back and revised some of my cache editing tutorials on Rune-Status (: (I've been telling people to repack like that for a while.)

**Closed** 2017-09-13 00:59 UTC
